### ISSUE TITLE
Invalid solar irradiance not considered for OLCI and MERIS4

### ISSUE THREAD

**Issue by marpet** [bcdev/s3tbx-c2rcc#54]
At the edges of the scene the solar_flux values can be -1 which means invalid.
This is not considered and thus the toa reflectances are wrong.
Also this leads to a bad histogram stretching because the values in the edge area are very low.

**Comment by RolandDo** [comment]
Hallo Marco,

kann ich jetzt die neue Version runterladen und dann ein neues Modul 
erzeugen?

Außerdem: man könnte ja auch eine Zeile bezüglich ozon einfügen
if ozone < 10  then multiply with the conversion factor

dann würde es auch für die alten MERIS 4rp Daten funktionieren

viele Grüße
Roland
Helmholtz-Zentrum Geesthacht 
Zentrum für Material- und Küstenforschung GmbH 
Max-Planck-Straße 1 I 21502 Geesthacht I Deutschland/Germany 

Geschäftsführer/Board of Management: Prof. Dr. Wolfgang Kaysser, Dipl.-Ing. Michael Ganß 
Vorsitzender des Aufsichtsrates/Chairman of the Supervisory Board: Ministerialdirigent Dr. Herbert Zeisel 
Amtsgericht Lübeck HRB 285 GE (Register Court) 
Internet: http://www.hzg.de

**Comment by marpet** [comment]
Ja, wenn du jetzt die Sourcen updatest und dann neu baust und das module dann installierst sollte es mit den neuen korrigierten Produkten funktionieren.

Stimmt, mit dem Ozon Test könnte man den Fehler in den Produkten abfangen. Vielleicht beim nächsten update.

**Comment by RolandDo** [comment]
dann baue ich bei mir den ozontest schon mal ein, da ich noch so viele 
alte Testdaten habe, die mir in der Auswahl von gestern fehlen 
VG
Roland



Von:    Marco Peters <notifications@github.com>
An:     bcdev/s3tbx-c2rcc <s3tbx-c2rcc@noreply.github.com>
Kopie:  RolandDo <roland.doerffer@brockmann-consult.de>, Comment 
<comment@noreply.github.com>
Datum:  10.05.2017 09:43
Betreff:        Re: [bcdev/s3tbx-c2rcc] Invalid solar irradiance not 
considered for OLCI and MERIS4 (#54)



Ja, wenn du jetzt die Sourcen updatest und dann neu baust und das module 
dann installierst sollte es mit den neuen korrigierten Produkten 
funktionieren.
Stimmt, mit dem Ozon Test könnte man den Fehler in den Produkten abfangen. 
Vielleicht beim nächsten update.
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.

Helmholtz-Zentrum Geesthacht 
Zentrum für Material- und Küstenforschung GmbH 
Max-Planck-Straße 1 I 21502 Geesthacht I Deutschland/Germany 

Geschäftsführer/Board of Management: Prof. Dr. Wolfgang Kaysser, Dipl.-Ing. Michael Ganß 
Vorsitzender des Aufsichtsrates/Chairman of the Supervisory Board: Ministerialdirigent Dr. Herbert Zeisel 
Amtsgericht Lübeck HRB 285 GE (Register Court) 
Internet: http://www.hzg.de

**Comment by RolandDo** [comment]
Ich habe jetzt in den MERIS4 Algorithmus eine Zeile eingefügt:

//*** (9.3.1) ozone correction ***/
double model_ozone = 0;
if(ozone > 1000){ozone /= 46698;}

viele Grüße
Roland



Von:    Marco Peters <notifications@github.com>
An:     bcdev/s3tbx-c2rcc <s3tbx-c2rcc@noreply.github.com>
Kopie:  RolandDo <roland.doerffer@brockmann-consult.de>, Comment 
<comment@noreply.github.com>
Datum:  10.05.2017 09:43
Betreff:        Re: [bcdev/s3tbx-c2rcc] Invalid solar irradiance not 
considered for OLCI and MERIS4 (#54)



Ja, wenn du jetzt die Sourcen updatest und dann neu baust und das module 
dann installierst sollte es mit den neuen korrigierten Produkten 
funktionieren.
Stimmt, mit dem Ozon Test könnte man den Fehler in den Produkten abfangen. 
Vielleicht beim nächsten update.
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.

Helmholtz-Zentrum Geesthacht 
Zentrum für Material- und Küstenforschung GmbH 
Max-Planck-Straße 1 I 21502 Geesthacht I Deutschland/Germany 

Geschäftsführer/Board of Management: Prof. Dr. Wolfgang Kaysser, Dipl.-Ing. Michael Ganß 
Vorsitzender des Aufsichtsrates/Chairman of the Supervisory Board: Ministerialdirigent Dr. Herbert Zeisel 
Amtsgericht Lübeck HRB 285 GE (Register Court) 
Internet: http://www.hzg.de

**Comment by RolandDo** [comment]
Hallo Marco,
beim Making des Programms bekomme ich folgende Fehlermeldung:

Information:10.05.2017 17:29 - Compilation completed with 1 error and 0 
warnings in 32ms
Error:Cannot run program "C:\Program Files\Java\jdk1.8.0_51\bin\java" (in 
directory "C:\Users\doerffer\.IdeaIC14\system\compile-server"): 
CreateProcess error=2, Das System kann die angegebene Datei nicht finden

ich hatte diese Meldung schon einmal, konnte das dann lösen. Irgendwo 
hatte ich angeklickt, dass so etwas wie embedded Java genutzt werden soll.

weiß nicht mehr wo
viele grüße
Roland



Von:    Marco Peters <notifications@github.com>
An:     bcdev/s3tbx-c2rcc <s3tbx-c2rcc@noreply.github.com>
Kopie:  RolandDo <roland.doerffer@brockmann-consult.de>, Comment 
<comment@noreply.github.com>
Datum:  10.05.2017 09:43
Betreff:        Re: [bcdev/s3tbx-c2rcc] Invalid solar irradiance not 
considered for OLCI and MERIS4 (#54)



Ja, wenn du jetzt die Sourcen updatest und dann neu baust und das module 
dann installierst sollte es mit den neuen korrigierten Produkten 
funktionieren.
Stimmt, mit dem Ozon Test könnte man den Fehler in den Produkten abfangen. 
Vielleicht beim nächsten update.
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.

Helmholtz-Zentrum Geesthacht 
Zentrum für Material- und Küstenforschung GmbH 
Max-Planck-Straße 1 I 21502 Geesthacht I Deutschland/Germany 

Geschäftsführer/Board of Management: Prof. Dr. Wolfgang Kaysser, Dipl.-Ing. Michael Ganß 
Vorsitzender des Aufsichtsrates/Chairman of the Supervisory Board: Ministerialdirigent Dr. Herbert Zeisel 
Amtsgericht Lübeck HRB 285 GE (Register Court) 
Internet: http://www.hzg.de

**Comment by RolandDo** [comment]
Hallo Marco,
das Java Problem habe ich gelöst. Allerdings sind die TOA reflectances 
immer noch weiß.
viele Grüße
Roland



Von:    Marco Peters <notifications@github.com>
An:     bcdev/s3tbx-c2rcc <s3tbx-c2rcc@noreply.github.com>
Kopie:  RolandDo <roland.doerffer@brockmann-consult.de>, Comment 
<comment@noreply.github.com>
Datum:  10.05.2017 09:43
Betreff:        Re: [bcdev/s3tbx-c2rcc] Invalid solar irradiance not 
considered for OLCI and MERIS4 (#54)



Ja, wenn du jetzt die Sourcen updatest und dann neu baust und das module 
dann installierst sollte es mit den neuen korrigierten Produkten 
funktionieren.
Stimmt, mit dem Ozon Test könnte man den Fehler in den Produkten abfangen. 
Vielleicht beim nächsten update.
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.

Helmholtz-Zentrum Geesthacht 
Zentrum für Material- und Küstenforschung GmbH 
Max-Planck-Straße 1 I 21502 Geesthacht I Deutschland/Germany 

Geschäftsführer/Board of Management: Prof. Dr. Wolfgang Kaysser, Dipl.-Ing. Michael Ganß 
Vorsitzender des Aufsichtsrates/Chairman of the Supervisory Board: Ministerialdirigent Dr. Herbert Zeisel 
Amtsgericht Lübeck HRB 285 GE (Register Court) 
Internet: http://www.hzg.de
